### ISSUE TITLE
无法获取B19

### ISSUE THREAD

**Issue by TTsdzb** [koishijs/koishi-plugin-phigros#1]
版本：2.0.2

日志如下：

```
2023-10-09 20:50:20 [W] command phigros.b19 
                        TypeError: Cannot read properties of undefined (reading 'chart')
                            at /home/pi/koishi/node_modules/.pnpm/koishi-plugin-phigros@2.0.2_koishi@4.15.0/node_modules/koishi-plugin-phigros/lib/index.js:197:63
                            at Array.map (<anonymous>)
                            at songRKS (/home/pi/koishi/node_modules/.pnpm/koishi-plugin-phigros@2.0.2_koishi@4.15.0/node_modules/koishi-plugin-phigros/lib/index.js:192:17)
                            at /home/pi/koishi/node_modules/.pnpm/koishi-plugin-phigros@2.0.2_koishi@4.15.0/node_modules/koishi-plugin-phigros/lib/index.js:203:34
                            at Array.map (<anonymous>)
                            at best (/home/pi/koishi/node_modules/.pnpm/koishi-plugin-phigros@2.0.2_koishi@4.15.0/node_modules/koishi-plugin-phigros/lib/index.js:203:23)
                            at rks (/home/pi/koishi/node_modules/.pnpm/koishi-plugin-phigros@2.0.2_koishi@4.15.0/node_modules/koishi-plugin-phigros/lib/index.js:208:16)
                            at _Command.<anonymous> (/home/pi/koishi/node_modules/.pnpm/koishi-plugin-phigros@2.0.2_koishi@4.15.0/node_modules/koishi-plugin-phigros/lib/index.js:935:21)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async Array.<anonymous> (/home/pi/koishi/node_modules/.pnpm/@koishijs+core@4.15.0/node_modules/@koishijs/core/lib/index.cjs:1659:14)
```

**Comment by mqnu00** [comment]
因为phigros有新歌，然后插件读取的songs.json歌曲信息还是旧的，然后就读不到chart歌曲的难度信息

**Comment by mqnu00** [comment]
我fork了修改了一些，插件也发布了，你可以看看
